# ================================================================
#  TrashBoy.ps1  |  Plex Unwatched Media Cleanup  |  v0.2.4
#  https://github.com/sfaith/TrashBoy
#
#  Identifies unwatched or rarely watched media across your Plex
#  libraries and optionally removes it via Sonarr, Radarr, or Lidarr.
#
#  QUICK START:
#    1. Copy TrashBoy.config.example.ps1 to TrashBoy.config.ps1
#    2. Edit TrashBoy.config.ps1 with your settings
#    3. Run: .\TrashBoy.ps1  (or double-click TrashBoy.bat)
#
#  HOW TO FIND YOUR PLEX TOKEN:
#    1. Open Plex Web in a browser and sign in
#    2. Browse to any library item, click (...) > Get Info > View XML
#    3. The URL will contain ?X-Plex-Token=YOURTOKEN -- copy that value
#    Full guide: https://support.plex.tv/articles/204059436
#
#  DATA SOURCES:
#    Tautulli (recommended, optional):
#      When TautulliConfig.Enabled = $true, play counts and last-played
#      dates come from Tautulli's history, which covers ALL users and
#      lets you set a MinWatchedPercent threshold (e.g. 50%) so a
#      3-minute accidental start is not counted as a watch.
#
#    Plex only (fallback):
#      When Tautulli is disabled, TrashBoy uses Plex's built-in
#      viewCount, which only reflects the server owner's account
#      and has no completion threshold.
#
#  HOW IT WORKS:
#    TV shows  : evaluated at series level. If any episode has been
#                played (above MinWatchedPercent) the series is excluded.
#    Music     : evaluated at artist level. If any track has been played
#                the artist is excluded.
#    Deletion  : always routed through the appropriate *arr app.
#                TrashBoy never deletes files directly.
#
#  REQUIREMENTS:
#    - PowerShell 5.1 or later
#    - TrashBoy.config.ps1 in the same folder as this script
#    - Network access to Plex, Tautulli (if enabled), and each *arr app
#
#  USER CONFIGURATION:
#    All settings live in TrashBoy.config.ps1. Do not edit this file.
# ================================================================

#Requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ================================================================
#  LOAD CONFIG
# ================================================================
$ConfigFile = Join-Path $PSScriptRoot 'TrashBoy.config.ps1'

if (-not (Test-Path -LiteralPath $ConfigFile)) {
    Write-Host ''
    Write-Host '  ============================================================' -ForegroundColor Red
    Write-Host '   TrashBoy -- Configuration file not found' -ForegroundColor Red
    Write-Host '  ============================================================' -ForegroundColor Red
    Write-Host ''
    Write-Host '  TrashBoy.config.ps1 was not found in the script folder.' -ForegroundColor Yellow
    Write-Host ''
    Write-Host '  To set up:' -ForegroundColor White
    Write-Host '    1. Copy TrashBoy.config.example.ps1 to TrashBoy.config.ps1' -ForegroundColor White
    Write-Host '    2. Open TrashBoy.config.ps1 and fill in your settings' -ForegroundColor White
    Write-Host '    3. Run TrashBoy again' -ForegroundColor White
    Write-Host ''
    Write-Host ("  Expected config path: {0}" -f $ConfigFile) -ForegroundColor DarkGray
    Write-Host ''
    exit
}

try {
    . $ConfigFile
} catch {
    Write-Host ''
    Write-Host '  ============================================================' -ForegroundColor Red
    Write-Host '   TrashBoy -- Error loading configuration' -ForegroundColor Red
    Write-Host '  ============================================================' -ForegroundColor Red
    Write-Host ''
    Write-Host '  TrashBoy.config.ps1 was found but could not be loaded.' -ForegroundColor Yellow
    Write-Host '  Check the file for syntax errors.' -ForegroundColor Yellow
    Write-Host ''
    Write-Host ("  Error: {0}" -f $_) -ForegroundColor Red
    Write-Host ''
    exit
}

$configErrors = @()
if ($null -eq $PlexConfig)     { $configErrors += '$PlexConfig is not defined' }
if ($null -eq $TautulliConfig) { $configErrors += '$TautulliConfig is not defined' }
if ($null -eq $RadarrConfig)   { $configErrors += '$RadarrConfig is not defined' }
if ($null -eq $SonarrConfig)   { $configErrors += '$SonarrConfig is not defined' }
if ($null -eq $LidarrConfig)   { $configErrors += '$LidarrConfig is not defined' }
if ($null -eq $LibraryMap)     { $configErrors += '$LibraryMap is not defined' }
if ($null -eq $ScanConfig)     { $configErrors += '$ScanConfig is not defined' }

if ($configErrors.Count) {
    Write-Host ''
    Write-Host '  ============================================================' -ForegroundColor Red
    Write-Host '   TrashBoy -- Incomplete configuration' -ForegroundColor Red
    Write-Host '  ============================================================' -ForegroundColor Red
    Write-Host ''
    Write-Host '  The following required variables are missing from TrashBoy.config.ps1:' -ForegroundColor Yellow
    foreach ($e in $configErrors) { Write-Host ("    - {0}" -f $e) -ForegroundColor Red }
    Write-Host ''
    Write-Host '  Compare your config file against TrashBoy.config.example.ps1.' -ForegroundColor White
    Write-Host ''
    exit
}

# Stamp API version onto *arr configs
$SonarrConfig.ApiVersion = 'v3'
$RadarrConfig.ApiVersion = 'v3'
$LidarrConfig.ApiVersion = 'v1'

# Tautulli defaults
if (-not $TautulliConfig.ContainsKey('Enabled'))           { $TautulliConfig.Enabled           = $false }
if (-not $TautulliConfig.ContainsKey('MinWatchedPercent')) { $TautulliConfig.MinWatchedPercent  = 50     }

# ScanConfig defaults and rename MaxViewCount -> MaxPlayCount for backward compat
if ($ScanConfig.ContainsKey('MaxViewCount') -and -not $ScanConfig.ContainsKey('MaxPlayCount')) {
    $ScanConfig.MaxPlayCount = $ScanConfig.MaxViewCount
}
if (-not $ScanConfig.ContainsKey('MaxPlayCount')) { $ScanConfig.MaxPlayCount = 0          }
if (-not $ScanConfig.ContainsKey('SortBy'))       { $ScanConfig.SortBy       = 'PlayCount' }

# ================================================================
#  SHARED HELPERS
# ================================================================
$Script:LogFile = $null

function Start-Log ([string]$Prefix) {
    $logDir = Join-Path $PSScriptRoot 'Logs'
    if (-not (Test-Path -LiteralPath $logDir)) {
        New-Item -ItemType Directory -Path $logDir -Force | Out-Null
    }
    $Script:LogFile = Join-Path $logDir ("{0}_{1}.log" -f $Prefix, (Get-Date -Format 'yyyyMMdd_HHmmss'))
}

function Write-Log {
    param([string]$Message, [string]$Color = 'White')
    Write-Host $Message -ForegroundColor $Color
    if ($Script:LogFile) {
        $Message | Out-File $Script:LogFile -Append -Encoding utf8
    }
}

function Write-SectionHeader ([string]$Title) {
    Write-Log ''
    Write-Log ('  ' + ('=' * 66)) 'Cyan'
    Write-Log ("  $Title") 'Cyan'
    Write-Log ('  ' + ('=' * 66)) 'Cyan'
}

function Write-Progress2 ([string]$Label, [int]$Current, [int]$Total, [string]$Item = '') {
    $truncated = if ($Item.Length -gt 50) { $Item.Substring(0, 47) + '...' } else { $Item }
    $line = '  {0} {1} / {2}  ({3})' -f $Label, $Current, $Total, $truncated
    Write-Host ("`r{0,-90}" -f $line) -NoNewline -ForegroundColor DarkGray
}

function Clear-Progress {
    Write-Host ("`r{0}" -f (' ' * 90)) -NoNewline
    Write-Host "`r" -NoNewline
}

function Format-Bytes ([long]$Bytes) {
    if ($Bytes -ge 1TB) { return ('{0:N2} TB' -f ($Bytes / 1TB)) }
    if ($Bytes -ge 1GB) { return ('{0:N2} GB' -f ($Bytes / 1GB)) }
    if ($Bytes -ge 1MB) { return ('{0:N1} MB' -f ($Bytes / 1MB)) }
    return ('{0} B' -f $Bytes)
}

function Confirm-LiveAction ([string]$Warning) {
    Write-Log ''
    Write-Log ("  WARNING: {0}" -f $Warning) 'Red'
    Write-Log '  This action cannot be undone. A log will be saved next to this script.' 'Yellow'
    Write-Log ''
    $confirm = Read-Host '  Type YES to proceed, or anything else to abort'
    if ($confirm.ToUpper() -ne 'YES') {
        Write-Log '  Aborted. No changes were made.' 'Yellow'
        return $false
    }
    Write-Log ''
    return $true
}

function Select-SubMode ([string]$Prompt, [string[]]$Options, [string]$Title = '') {
    Write-Host ''
    if ($Title) {
        Write-Host ("  {0}" -f $Title) -ForegroundColor White
        Write-Host ("  {0}" -f $Prompt) -ForegroundColor Cyan
    } else {
        Write-Host ("  {0}" -f $Prompt) -ForegroundColor Cyan
    }
    Write-Host ''
    for ($i = 0; $i -lt $Options.Count; $i++) {
        Write-Host ("    ({0}) {1}" -f ($i + 1), $Options[$i])
    }
    Write-Host '    (M) Return to main menu' -ForegroundColor DarkGray
    Write-Host '    (Q) Quit TrashBoy'       -ForegroundColor DarkGray
    Write-Host ''
    do {
        $c = Read-Host '  Choice'
        if ($c.ToUpper() -eq 'M') { return 0  }
        if ($c.ToUpper() -eq 'Q') { return -1 }
        $idx = 0
        $valid = [int]::TryParse($c, [ref]$idx) -and $idx -ge 1 -and $idx -le $Options.Count
    } until ($valid)
    return $idx
}

# ================================================================
#  PLEX API
# ================================================================
function Invoke-PlexApi ([string]$Path, [hashtable]$Query = @{}) {
    $uri = "$($PlexConfig.BaseUrl.TrimEnd('/'))$Path`?X-Plex-Token=$($PlexConfig.Token)"
    foreach ($k in $Query.Keys) {
        $uri += "&$k=$([Uri]::EscapeDataString($Query[$k]))"
    }
    try {
        # Use Invoke-WebRequest and decode bytes explicitly as UTF-8 to prevent
        # PowerShell misinterpreting non-ASCII characters (e.g. ö, ü, ô) as Latin-1,
        # which causes display corruption like MÃ¶tley CrÃ¼e instead of Mötley Crüe.
        $progressPreference = $ProgressPreference
        $ProgressPreference = 'SilentlyContinue'
        $response = Invoke-WebRequest -Uri $uri -Headers @{ Accept = 'application/json' } -Method Get -UseBasicParsing -ErrorAction Stop
        $ProgressPreference = $progressPreference
        $json     = [System.Text.Encoding]::UTF8.GetString($response.RawContentStream.ToArray())
        return $json | ConvertFrom-Json
    } catch {
        Write-Log ("  [ERROR] Plex API {0} -- {1}" -f $Path, $_) 'Red'
        return $null
    }
}

function Get-PlexLibraries {
    $data = Invoke-PlexApi -Path '/library/sections'
    if (-not $data) { return @() }
    return $data.MediaContainer.Directory
}

function Get-PlexSectionId ([string]$LibraryName) {
    $libs = Get-PlexLibraries
    $match = $libs | Where-Object { $_.title -eq $LibraryName } | Select-Object -First 1
    return if ($match) { $match.key } else { $null }
}

# ================================================================
#  TAUTULLI API
# ================================================================
function Invoke-TautulliApi ([string]$Command, [hashtable]$Params = @{}) {
    $uri = "$($TautulliConfig.BaseUrl.TrimEnd('/'))/api/v2?apikey=$($TautulliConfig.ApiKey)&cmd=$Command"
    foreach ($k in $Params.Keys) {
        $uri += "&$k=$([Uri]::EscapeDataString($Params[$k].ToString()))"
    }
    try {
        $response = Invoke-RestMethod -Uri $uri -Method Get -ErrorAction Stop
        if ($response.response.result -eq 'success') {
            return $response.response.data
        } else {
            Write-Log ("  [ERROR] Tautulli {0} -- {1}" -f $Command, $response.response.message) 'Red'
            return $null
        }
    } catch {
        Write-Log ("  [ERROR] Tautulli API {0} -- {1}" -f $Command, $_) 'Red'
        return $null
    }
}

# Build a hashtable of rating_key -> qualifying play count from Tautulli
# Uses get_library_media_info which returns play_count and last_played per item
# Paginates automatically since large libraries may exceed the default page size.
function Get-TautulliPlayData ([string]$SectionId, [string]$LibraryType) {
    $playData   = @{}   # rating_key (string) -> @{ PlayCount = int; LastPlayed = DateTime|null }
    $pageSize   = 1000
    $start      = 0
    $totalItems = $null

    do {
        $params = @{
            section_id   = $SectionId
            length       = $pageSize
            start        = $start
            order_column = 'added_at'
            order_dir    = 'asc'
        }

        $page = Invoke-TautulliApi -Command 'get_library_media_info' -Params $params
        if (-not $page) { break }

        if ($null -eq $totalItems) {
            $totalItems = [int]$page.recordsTotal
        }

        $rows = $page.data
        if (-not $rows -or $rows.Count -eq 0) { break }

        foreach ($row in $rows) {
            $ratingKey = $row.rating_key.ToString()
            $rawCount  = if ($row.play_count) { [int]$row.play_count } else { 0 }
            $lastPlayed = $null
            if ($row.last_played -and [long]$row.last_played -gt 0) {
                $lastPlayed = [DateTimeOffset]::FromUnixTimeSeconds([long]$row.last_played).LocalDateTime
            }
            $playData[$ratingKey] = @{ PlayCount = $rawCount; LastPlayed = $lastPlayed }
        }

        $start += $rows.Count
    } while ($start -lt $totalItems)

    return $playData
}

# For TV shows: Tautulli's get_library_media_info at the show level returns
# aggregate play counts across all episodes. We use grandparent_rating_key
# matching via get_history to check per-episode completion, but that is
# expensive at scale. Instead we use the show-level play_count from
# get_library_media_info (section_type=show returns show rows), and trust
# that a show with play_count > 0 means at least one episode was watched.
# The MinWatchedPercent check is applied at the history level for movies;
# for shows we accept the show-level count and let the threshold filter.

function Get-TautulliHistoryPlayCount ([string]$RatingKey, [string]$MediaType) {
    # Returns the count of history entries for this item that meet MinWatchedPercent.
    # Used to validate movie play counts against the completion threshold.
    $minPct  = [int]$TautulliConfig.MinWatchedPercent
    $start   = 0
    $pgSize  = 100
    $qualifying = 0
    $total   = $null

    do {
        $params = @{
            rating_key = $RatingKey
            length     = $pgSize
            start      = $start
        }
        $page = Invoke-TautulliApi -Command 'get_history' -Params $params
        if (-not $page) { break }

        if ($null -eq $total) { $total = [int]$page.recordsTotal }
        $rows = $page.data
        if (-not $rows -or $rows.Count -eq 0) { break }

        foreach ($row in $rows) {
            $pct = if ($row.percent_complete) { [int]$row.percent_complete } else { 0 }
            if ($pct -ge $minPct) { $qualifying++ }
        }
        $start += $rows.Count
    } while ($start -lt $total)

    return $qualifying
}

# ================================================================
#  *ARR API
# ================================================================
function Invoke-ArrGet ([hashtable]$Config, [string]$Endpoint) {
    $uri = "$($Config.BaseUrl.TrimEnd('/'))/api/$($Config.ApiVersion)/$Endpoint"
    try {
        return Invoke-RestMethod -Uri $uri -Headers @{ 'X-Api-Key' = $Config.ApiKey } -Method Get -ErrorAction Stop
    } catch {
        Write-Log ("  [ERROR] GET {0} -- {1}" -f $uri, $_) 'Red'
        return $null
    }
}

function Invoke-ArrDelete ([hashtable]$Config, [string]$Endpoint) {
    $uri = "$($Config.BaseUrl.TrimEnd('/'))/api/$($Config.ApiVersion)/$Endpoint"
    try {
        Invoke-RestMethod -Uri $uri -Headers @{ 'X-Api-Key' = $Config.ApiKey } -Method Delete -ErrorAction Stop | Out-Null
        return $true
    } catch {
        Write-Log ("  [ERROR] DELETE {0} -- {1}" -f $uri, $_) 'Red'
        return $false
    }
}

# ================================================================
#  CONNECTION CHECK
# ================================================================
$Script:ConnectionStatus = @{
    Plex     = $false
    Tautulli = $false
    Sonarr   = $false
    Radarr   = $false
    Lidarr   = $false
}

function Invoke-ConnectionCheck {
    Write-Host ''
    Write-Host '  ============================================================' -ForegroundColor Cyan
    Write-Host '   TrashBoy  |  Connection Check' -ForegroundColor Cyan
    Write-Host '  ============================================================' -ForegroundColor Cyan
    Write-Host ''

    # Plex
    $plexStatus = Invoke-PlexApi -Path '/identity'
    if ($plexStatus) {
        $Script:ConnectionStatus.Plex = $true
        Write-Host ("  {0,-10}  [OK]  {1}" -f 'Plex', $PlexConfig.BaseUrl) -ForegroundColor Green
    } else {
        Write-Host ("  {0,-10}  [FAIL]  Cannot reach {1}" -f 'Plex', $PlexConfig.BaseUrl) -ForegroundColor Red
    }

    # Tautulli
    if ($TautulliConfig.Enabled) {
        $tautulliStatus = Invoke-TautulliApi -Command 'get_server_info'
        if ($tautulliStatus) {
            $Script:ConnectionStatus.Tautulli = $true
            Write-Host ("  {0,-10}  [OK]  {1}  (MinWatchedPercent: {2}%)" -f `
                'Tautulli', $TautulliConfig.BaseUrl, $TautulliConfig.MinWatchedPercent) -ForegroundColor Green
        } else {
            Write-Host ("  {0,-10}  [FAIL]  Cannot reach {1}" -f 'Tautulli', $TautulliConfig.BaseUrl) -ForegroundColor Red
            Write-Host ("  {0,-10}  Will fall back to Plex viewCount for play data." -f '') -ForegroundColor Yellow
        }
    } else {
        Write-Host ("  {0,-10}  Disabled -- using Plex viewCount as play source" -f 'Tautulli') -ForegroundColor DarkGray
    }

    # *arr apps
    foreach ($pair in @(
        @{ Name = 'Sonarr'; Config = $SonarrConfig; Key = 'Sonarr' }
        @{ Name = 'Radarr'; Config = $RadarrConfig; Key = 'Radarr' }
        @{ Name = 'Lidarr'; Config = $LidarrConfig; Key = 'Lidarr' }
    )) {
        if (-not $pair.Config.Enabled) {
            Write-Host ("  {0,-10}  Disabled" -f $pair.Name) -ForegroundColor DarkGray
            continue
        }
        $status = Invoke-ArrGet $pair.Config 'system/status'
        if ($status) {
            $Script:ConnectionStatus[$pair.Key] = $true
            Write-Host ("  {0,-10}  [OK]  v{1}" -f $pair.Name, $status.version) -ForegroundColor Green
        } else {
            Write-Host ("  {0,-10}  [FAIL]  Cannot reach {1}" -f $pair.Name, $pair.Config.BaseUrl) -ForegroundColor Red
        }
    }

    Write-Host ''
    if (-not $Script:ConnectionStatus.Plex) {
        Write-Host '  [WARN] Plex is unreachable. TrashBoy cannot scan without Plex.' -ForegroundColor Red
        Write-Host '  Check PlexConfig.BaseUrl and PlexConfig.Token in TrashBoy.config.ps1.' -ForegroundColor Yellow
    }
    Write-Host ''
}

Invoke-ConnectionCheck

# ================================================================
#  PLAY DATA: unified source (Tautulli or Plex)
# ================================================================

# Returns: @{ PlayCount = int; LastPlayed = DateTime|null }
# Source is Tautulli when enabled and connected, Plex viewCount otherwise.
# For Tautulli movie plays, applies MinWatchedPercent via get_history.
# For Tautulli TV/music, uses show/artist-level play_count from get_library_media_info.
$Script:TautulliCache = @{}   # section_id -> hashtable of rating_key -> play data

function Get-TautulliSectionCache ([string]$SectionId, [string]$LibraryType) {
    if (-not $Script:TautulliCache.ContainsKey($SectionId)) {
        Clear-Progress
        Write-Host ("  Loading Tautulli play data for section {0}..." -f $SectionId) -ForegroundColor DarkGray
        $Script:TautulliCache[$SectionId] = Get-TautulliPlayData -SectionId $SectionId -LibraryType $LibraryType
        Write-Host ("    {0} item(s) loaded from Tautulli." -f $Script:TautulliCache[$SectionId].Count) -ForegroundColor DarkGray
    }
    return $Script:TautulliCache[$SectionId]
}

function Get-PlayInfo ([string]$RatingKey, [string]$SectionId, [string]$LibraryType, [int]$PlexViewCount, [nullable[DateTime]]$PlexLastViewed) {
    # Returns [int]$PlayCount, [DateTime|null]$LastPlayed

    $useTautulli = $TautulliConfig.Enabled -and $Script:ConnectionStatus.Tautulli

    if ($useTautulli) {
        $cache = Get-TautulliSectionCache -SectionId $SectionId -LibraryType $LibraryType
        if ($cache.ContainsKey($RatingKey)) {
            $entry = $cache[$RatingKey]
            $rawCount = [int]$entry.PlayCount

            # For movies: validate against MinWatchedPercent via history
            # For shows/artists: trust the aggregate count from get_library_media_info
            if ($LibraryType -eq 'movie' -and $rawCount -gt 0 -and $TautulliConfig.MinWatchedPercent -gt 0) {
                $qualifying = Get-TautulliHistoryPlayCount -RatingKey $RatingKey -MediaType $LibraryType
                return @{ PlayCount = $qualifying; LastPlayed = $entry.LastPlayed }
            }
            return @{ PlayCount = $rawCount; LastPlayed = $entry.LastPlayed }
        }
        # Item not in Tautulli (never played) -- treat as 0
        return @{ PlayCount = 0; LastPlayed = $null }
    }

    # Plex fallback
    return @{ PlayCount = $PlexViewCount; LastPlayed = $PlexLastViewed }
}

# ================================================================
#  SCAN: Get unwatched items from Plex libraries
# ================================================================
function Get-ItemSizeBytes ([object]$MediaNode) {
    $total = [long]0
    if ($MediaNode.PSObject.Properties['Media'] -and $MediaNode.Media) {
        foreach ($m in $MediaNode.Media) {
            if ($m.PSObject.Properties['Part'] -and $m.Part) {
                foreach ($p in $m.Part) {
                    if ($p.PSObject.Properties['size'] -and $p.size) { $total += [long]$p.size }
                }
            }
        }
    }
    return $total
}

function Get-GuidValue ([object]$Item, [string]$Scheme) {
    if ($Item.PSObject.Properties['Guid'] -and $Item.Guid) {
        $hit = $Item.Guid | Where-Object { $_.PSObject.Properties['id'] -and $_.id -like "$Scheme`://*" } | Select-Object -First 1
        if ($hit) { return ($hit.id -replace "$Scheme`://", '') }
    }
    return ''
}

function Get-UnwatchedFromLibrary {
    param([PSObject]$Library, [int]$MaxPlays)

    $libKey   = $Library.key        # Plex section id
    $libName  = $Library.title
    $libType  = $Library.type       # movie | show | artist | photo
    $service  = if ($LibraryMap.ContainsKey($libName)) { $LibraryMap[$libName] } else { $null }
    $results  = [System.Collections.Generic.List[PSObject]]::new()

    switch ($libType) {

        # ── MOVIES ────────────────────────────────────────────────────────────
        'movie' {
            $data = Invoke-PlexApi -Path "/library/sections/$libKey/all"
            if (-not $data) { return $results }
            $items = $data.MediaContainer.Metadata
            if (-not $items) { return $results }

            $idx = 0
            foreach ($item in $items) {
                $idx++
                Write-Progress2 'Scanning movies...' $idx $items.Count $item.title

                $plexViews    = if ($item.PSObject.Properties['viewCount'])    { [int]$item.viewCount }    else { 0 }
                $plexLastView = if ($item.PSObject.Properties['lastViewedAt']) {
                    [DateTimeOffset]::FromUnixTimeSeconds([long]$item.lastViewedAt).LocalDateTime
                } else { $null }

                $playInfo = Get-PlayInfo `
                    -RatingKey      $item.ratingKey `
                    -SectionId      $libKey `
                    -LibraryType    'movie' `
                    -PlexViewCount  $plexViews `
                    -PlexLastViewed $plexLastView

                if ($playInfo.PlayCount -gt $MaxPlays) { continue }

                $addedAt   = [DateTimeOffset]::FromUnixTimeSeconds([long]$item.addedAt).LocalDateTime
                $sizeBytes = Get-ItemSizeBytes $item

                $results.Add([PSCustomObject]@{
                    Library       = $libName
                    Type          = 'Movie'
                    Title         = $item.title
                    Year          = if ($item.PSObject.Properties['year']) { [int]$item.year } else { 0 }
                    PlayCount     = $playInfo.PlayCount
                    LastPlayed    = $playInfo.LastPlayed
                    DateAdded     = $addedAt
                    DaysOld       = ([DateTime]::Now - $addedAt).Days
                    SizeBytes     = $sizeBytes
                    SizeHuman     = Format-Bytes $sizeBytes
                    GuidTmdb      = Get-GuidValue $item 'tmdb'
                    GuidImdb      = Get-GuidValue $item 'imdb'
                    GuidTvdb      = ''
                    GuidMbrainz   = ''
                    Service       = $service
                    PlexKey       = $item.ratingKey
                    PlexSectionId = $libKey
                })
            }
            Clear-Progress
        }

        # ── TV SHOWS ──────────────────────────────────────────────────────────
        'show' {
            $data = Invoke-PlexApi -Path "/library/sections/$libKey/all"
            if (-not $data) { return $results }
            $shows = $data.MediaContainer.Metadata
            if (-not $shows) { return $results }

            $idx = 0
            foreach ($show in $shows) {
                $idx++
                Write-Progress2 'Scanning shows...' $idx $shows.Count $show.title

                # For Tautulli: use show-level play count (aggregate across episodes)
                # For Plex: scan episodes individually to get max play count
                $plexShowViews    = if ($show.PSObject.Properties['viewCount'])    { [int]$show.viewCount }    else { 0 }
                $plexShowLastView = if ($show.PSObject.Properties['lastViewedAt']) {
                    [DateTimeOffset]::FromUnixTimeSeconds([long]$show.lastViewedAt).LocalDateTime
                } else { $null }

                $playInfo = Get-PlayInfo `
                    -RatingKey      $show.ratingKey `
                    -SectionId      $libKey `
                    -LibraryType    'show' `
                    -PlexViewCount  $plexShowViews `
                    -PlexLastViewed $plexShowLastView

                # Plex fallback needs episode-level check
                if (-not ($TautulliConfig.Enabled -and $Script:ConnectionStatus.Tautulli)) {
                    $epData   = Invoke-PlexApi -Path "/library/metadata/$($show.ratingKey)/allLeaves"
                    $episodes = if ($epData -and $epData.PSObject.Properties['MediaContainer'] -and $epData.MediaContainer.PSObject.Properties['Metadata']) {
                        $epData.MediaContainer.Metadata
                    } else { @() }
                    $maxEpViews = 0
                    foreach ($ep in $episodes) {
                        $v = if ($ep.PSObject.Properties['viewCount']) { [int]$ep.viewCount } else { 0 }
                        if ($v -gt $maxEpViews) { $maxEpViews = $v }
                    }
                    $playInfo.PlayCount = $maxEpViews
                }

                if ($playInfo.PlayCount -gt $MaxPlays) { continue }

                # Compute size from episodes
                $totalSize = [long]0
                $epData2 = Invoke-PlexApi -Path "/library/metadata/$($show.ratingKey)/allLeaves"
                if ($epData2 -and $epData2.PSObject.Properties['MediaContainer'] -and $epData2.MediaContainer.PSObject.Properties['Metadata'] -and $epData2.MediaContainer.Metadata) {
                    foreach ($ep in $epData2.MediaContainer.Metadata) {
                        $totalSize += Get-ItemSizeBytes $ep
                    }
                }

                $addedAt = [DateTimeOffset]::FromUnixTimeSeconds([long]$show.addedAt).LocalDateTime

                $results.Add([PSCustomObject]@{
                    Library       = $libName
                    Type          = 'TVShow'
                    Title         = $show.title
                    Year          = if ($show.PSObject.Properties['year']) { [int]$show.year } else { 0 }
                    PlayCount     = $playInfo.PlayCount
                    LastPlayed    = $playInfo.LastPlayed
                    DateAdded     = $addedAt
                    DaysOld       = ([DateTime]::Now - $addedAt).Days
                    SizeBytes     = $totalSize
                    SizeHuman     = Format-Bytes $totalSize
                    GuidTmdb      = ''
                    GuidImdb      = Get-GuidValue $show 'imdb'
                    GuidTvdb      = Get-GuidValue $show 'tvdb'
                    GuidMbrainz   = ''
                    Service       = $service
                    PlexKey       = $show.ratingKey
                    PlexSectionId = $libKey
                })
            }
            Clear-Progress
        }

        # ── MUSIC ─────────────────────────────────────────────────────────────
        'artist' {
            $data = Invoke-PlexApi -Path "/library/sections/$libKey/all"
            if (-not $data) { return $results }
            $artists = $data.MediaContainer.Metadata
            if (-not $artists) { return $results }

            $idx = 0
            foreach ($artist in $artists) {
                $idx++
                Write-Progress2 'Scanning artists...' $idx $artists.Count $artist.title

                $plexViews    = if ($artist.PSObject.Properties['viewCount']) { [int]$artist.viewCount } else { 0 }
                $plexLastView = $null

                $playInfo = Get-PlayInfo `
                    -RatingKey      $artist.ratingKey `
                    -SectionId      $libKey `
                    -LibraryType    'artist' `
                    -PlexViewCount  $plexViews `
                    -PlexLastViewed $plexLastView

                # Plex fallback: scan tracks
                if (-not ($TautulliConfig.Enabled -and $Script:ConnectionStatus.Tautulli)) {
                    $trackData = Invoke-PlexApi -Path "/library/metadata/$($artist.ratingKey)/allLeaves"
                    $tracks    = if ($trackData -and $trackData.PSObject.Properties['MediaContainer'] -and $trackData.MediaContainer.PSObject.Properties['Metadata']) {
                        $trackData.MediaContainer.Metadata
                    } else { @() }
                    $maxTrackViews = 0
                    foreach ($t in $tracks) {
                        $v = if ($t.PSObject.Properties['viewCount']) { [int]$t.viewCount } else { 0 }
                        if ($v -gt $maxTrackViews) { $maxTrackViews = $v }
                    }
                    $playInfo.PlayCount = $maxTrackViews
                }

                if ($playInfo.PlayCount -gt $MaxPlays) { continue }

                # Compute size from tracks
                $totalSize = [long]0
                $trackData2 = Invoke-PlexApi -Path "/library/metadata/$($artist.ratingKey)/allLeaves"
                if ($trackData2 -and $trackData2.PSObject.Properties['MediaContainer'] -and $trackData2.MediaContainer.PSObject.Properties['Metadata'] -and $trackData2.MediaContainer.Metadata) {
                    foreach ($t in $trackData2.MediaContainer.Metadata) {
                        $totalSize += Get-ItemSizeBytes $t
                    }
                }

                $addedAt = [DateTimeOffset]::FromUnixTimeSeconds([long]$artist.addedAt).LocalDateTime

                $results.Add([PSCustomObject]@{
                    Library       = $libName
                    Type          = 'Artist'
                    Title         = $artist.title
                    Year          = 0
                    PlayCount     = $playInfo.PlayCount
                    LastPlayed    = $playInfo.LastPlayed
                    DateAdded     = $addedAt
                    DaysOld       = ([DateTime]::Now - $addedAt).Days
                    SizeBytes     = $totalSize
                    SizeHuman     = Format-Bytes $totalSize
                    GuidTmdb      = ''
                    GuidImdb      = ''
                    GuidTvdb      = ''
                    GuidMbrainz   = Get-GuidValue $artist 'musicbrainz'
                    Service       = $service
                    PlexKey       = $artist.ratingKey
                    PlexSectionId = $libKey
                })
            }
            Clear-Progress
        }

        default { }  # photo libraries etc -- silently skip
    }

    return $results
}

# ================================================================
#  *ARR DELETION
# ================================================================
function Remove-ViaRadarr ([PSObject]$Item, [bool]$WithFiles) {
    $movies = Invoke-ArrGet $RadarrConfig 'movie'
    if (-not $movies) { return $false }

    $match = $null
    if ($Item.GuidTmdb) {
        $tmdbId = try { [int]$Item.GuidTmdb } catch { 0 }
        if ($tmdbId) { $match = $movies | Where-Object { $_.tmdbId -eq $tmdbId } | Select-Object -First 1 }
    }
    if (-not $match -and $Item.GuidImdb) {
        $match = $movies | Where-Object { $_.imdbId -eq $Item.GuidImdb } | Select-Object -First 1
    }
    if (-not $match) {
        $match = $movies | Where-Object { $_.title -eq $Item.Title } | Select-Object -First 1
    }
    if (-not $match) {
        Write-Log ("  [NO MATCH] Radarr has no record of '{0}' -- skipped" -f $Item.Title) 'Yellow'
        return $false
    }

    $deleteFlag = $WithFiles.ToString().ToLower()
    $ok = Invoke-ArrDelete $RadarrConfig "movie/$($match.id)?deleteFiles=$deleteFlag&addImportExclusion=false"
    if ($ok) { Write-Log ("  [DELETED]  [Radarr] {0}" -f $Item.Title) 'Green' }
    return $ok
}

function Remove-ViaSonarr ([PSObject]$Item, [bool]$WithFiles) {
    $series = Invoke-ArrGet $SonarrConfig 'series'
    if (-not $series) { return $false }

    $match = $null
    if ($Item.GuidTvdb) {
        $tvdbId = try { [int]$Item.GuidTvdb } catch { 0 }
        if ($tvdbId) { $match = $series | Where-Object { $_.tvdbId -eq $tvdbId } | Select-Object -First 1 }
    }
    if (-not $match -and $Item.GuidImdb) {
        $match = $series | Where-Object { $_.imdbId -eq $Item.GuidImdb } | Select-Object -First 1
    }
    if (-not $match) {
        $match = $series | Where-Object { $_.title -eq $Item.Title } | Select-Object -First 1
    }
    if (-not $match) {
        Write-Log ("  [NO MATCH] Sonarr has no record of '{0}' -- skipped" -f $Item.Title) 'Yellow'
        return $false
    }

    $deleteFlag = $WithFiles.ToString().ToLower()
    $ok = Invoke-ArrDelete $SonarrConfig "series/$($match.id)?deleteFiles=$deleteFlag"
    if ($ok) { Write-Log ("  [DELETED]  [Sonarr] {0}" -f $Item.Title) 'Green' }
    return $ok
}

function Remove-ViaLidarr ([PSObject]$Item, [bool]$WithFiles) {
    $artists = Invoke-ArrGet $LidarrConfig 'artist'
    if (-not $artists) { return $false }

    $match = $null
    if ($Item.GuidMbrainz) {
        $match = $artists | Where-Object { $_.foreignArtistId -eq $Item.GuidMbrainz } | Select-Object -First 1
    }
    if (-not $match) {
        $match = $artists | Where-Object { $_.artistName -eq $Item.Title } | Select-Object -First 1
    }
    if (-not $match) {
        Write-Log ("  [NO MATCH] Lidarr has no record of '{0}' -- skipped" -f $Item.Title) 'Yellow'
        return $false
    }

    $deleteFlag = $WithFiles.ToString().ToLower()
    $ok = Invoke-ArrDelete $LidarrConfig "artist/$($match.id)?deleteFiles=$deleteFlag"
    if ($ok) { Write-Log ("  [DELETED]  [Lidarr] {0}" -f $Item.Title) 'Green' }
    return $ok
}

# ================================================================
#  SCAN + REPORT (TOOL 1)
# ================================================================
function Invoke-UnwatchedScan {
    param([string[]]$FilterLibraries = @())

    Start-Log 'TrashBoy_Scan'

    $dataSource = if ($TautulliConfig.Enabled -and $Script:ConnectionStatus.Tautulli) {
        "Tautulli (MinWatchedPercent: $($TautulliConfig.MinWatchedPercent)%)"
    } else {
        'Plex viewCount (Tautulli disabled or unreachable)'
    }

    # ── Runtime override for MaxPlayCount ─────────────────────────────────────
    $effectiveMaxPlays = $ScanConfig.MaxPlayCount
    Write-Host ''
    Write-Host ("  Max play count threshold  [{0}] -- press Enter to accept, or type a number to override:" -f $effectiveMaxPlays) -ForegroundColor Cyan
    $overrideInput = Read-Host '  Threshold'
    if ($overrideInput.Trim() -ne '') {
        $parsed = 0
        if ([int]::TryParse($overrideInput.Trim(), [ref]$parsed) -and $parsed -ge 0) {
            $effectiveMaxPlays = $parsed
            Write-Host ("  Using override: {0}" -f $effectiveMaxPlays) -ForegroundColor Yellow
        } else {
            Write-Host ("  Invalid input -- using config default: {0}" -f $effectiveMaxPlays) -ForegroundColor Yellow
        }
    }
    # ──────────────────────────────────────────────────────────────────────────

    Write-Log ''
    Write-Log '  ============================================================' 'Cyan'
    Write-Log '   TrashBoy  |  Unwatched Media Report' 'Cyan'
    Write-Log ('   {0}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')) 'Cyan'
    Write-Log '  ============================================================' 'Cyan'
    Write-Log ''
    Write-Log ("  Play data source   : {0}" -f $dataSource) 'White'
    Write-Log ("  Max play count     : {0}{1}" -f $effectiveMaxPlays, $(if ($effectiveMaxPlays -ne $ScanConfig.MaxPlayCount) { '  (overridden from config)' } else { '' })) 'White'
    Write-Log ("  Sort by            : {0}" -f $ScanConfig.SortBy) 'White'
    Write-Log ''

    if (-not $Script:ConnectionStatus.Plex) {
        Write-Log '  Plex is not reachable. Cannot scan.' 'Red'
        return $null
    }

    # Clear Tautulli section cache for fresh scan
    $Script:TautulliCache = @{}

    Write-Log '  Discovering Plex libraries...' 'DarkGray'
    $allLibraries = Get-PlexLibraries
    if (-not $allLibraries -or $allLibraries.Count -eq 0) {
        Write-Log '  No libraries found in Plex. Check PlexConfig.' 'Red'
        return $null
    }

    foreach ($lib in $allLibraries) {
        $svc = if ($LibraryMap.ContainsKey($lib.title)) { $LibraryMap[$lib.title] } else { '(unmapped -- will skip)' }
        Write-Log ("  {0,-35} [{1}]  → {2}" -f $lib.title, $lib.type, $svc) 'DarkGray'
    }

    # Filter to mapped libraries only (unmapped = no *arr service = nothing to scan or delete)
    $mappedLibraries = $allLibraries | Where-Object { $LibraryMap.ContainsKey($_.title) }
    $skippedLibraries = @($allLibraries | Where-Object { -not $LibraryMap.ContainsKey($_.title) })
    if ($skippedLibraries.Count -gt 0) {
        Write-Log ''
        Write-Log ("  Skipping {0} unmapped library/libraries: {1}" -f `
            $skippedLibraries.Count, ($skippedLibraries.title -join ', ')) 'DarkGray'
        Write-Log '  Add libraries to $LibraryMap in TrashBoy.config.ps1 to include them.' 'DarkGray'
    }

    if ($FilterLibraries.Count -gt 0) {
        $mappedLibraries = $mappedLibraries | Where-Object { $FilterLibraries -contains $_.title }
        Write-Log ''
        Write-Log ("  Filtered to: {0}" -f ($FilterLibraries -join ', ')) 'Cyan'
    }

    Write-Log ''
    Write-SectionHeader ('SCANNING -- plays <= {0}' -f $effectiveMaxPlays)
    Write-Log ''

    $allUnwatched = [System.Collections.Generic.List[PSObject]]::new()

    foreach ($lib in $mappedLibraries) {
        Write-Log ("  {0}  [{1}]" -f $lib.title, $lib.type) 'White'
        $items = Get-UnwatchedFromLibrary -Library $lib -MaxPlays $effectiveMaxPlays
        $count = $items.Count
        foreach ($i in $items) { $allUnwatched.Add($i) }
        $color = if ($count -gt 0) { 'Yellow' } else { 'Green' }
        Write-Log ("    {0} unwatched item(s) found" -f $count) $color
    }

    $sorted = switch ($ScanConfig.SortBy) {
        'PlayCount' { $allUnwatched | Sort-Object PlayCount, DateAdded }
        'DateAdded' { $allUnwatched | Sort-Object DateAdded }
        'Title'     { $allUnwatched | Sort-Object Title }
        'Size'      { $allUnwatched | Sort-Object SizeBytes -Descending }
        default     { $allUnwatched | Sort-Object PlayCount, DateAdded }
    }

    Write-Log ''
    Write-SectionHeader ('REPORT -- {0} item(s) flagged' -f $sorted.Count)

    if ($sorted.Count -eq 0) {
        Write-Log ''
        Write-Log '  No unwatched media found. Your library is fully watched!' 'Green'
        Write-Log ''
        Write-Log ("  Log saved to: {0}" -f $Script:LogFile) 'Cyan'
        return @()
    }

    $totalBytes = ($sorted | Measure-Object -Property SizeBytes -Sum).Sum
    Write-Log ''
    Write-Log ("  Play data source        : {0}" -f $dataSource) 'DarkGray'
    Write-Log ("  Total reclaimable space : {0}" -f (Format-Bytes $totalBytes)) 'Cyan'
    Write-Log ''

    $grouped = $sorted | Group-Object Library
    foreach ($group in $grouped) {
        $groupBytes = ($group.Group | Measure-Object -Property SizeBytes -Sum).Sum
        Write-Log ("  ┌── {0}" -f $group.Name) 'DarkCyan'
        foreach ($item in $group.Group) {
            $lastStr  = if ($item.LastPlayed) { $item.LastPlayed.ToString('yyyy-MM-dd') } else { 'never    ' }
            $svcLabel = if ($item.Service) { "[{0}]" -f $item.Service } else { '[unmapped]' }
            $yearStr  = if ($item.Year -gt 0) { "({0})" -f $item.Year } else { '      ' }
            $titleFull = '{0} {1}' -f $item.Title, $yearStr
            $color = if ($item.PlayCount -eq 0) { 'White' } else { 'DarkYellow' }
            Write-Log ("  │  {0,-52} Plays:{1,3}  Added:{2:yyyy-MM-dd}  Last:{3}  {4,10}  {5}" -f `
                $titleFull, $item.PlayCount, $item.DateAdded, $lastStr, $item.SizeHuman, $svcLabel) $color
        }
        Write-Log ("  └── {0} item(s)  |  {1}" -f $group.Count, (Format-Bytes $groupBytes)) 'DarkCyan'
        Write-Log ''
    }

    $Script:LastScanResults = [array]$sorted
    return [array]$sorted
}

# ================================================================
#  SHARED: Item list display
#  Used by both the scan report and the pre-delete review
# ================================================================
function Show-ItemList {
    param(
        [array]$Items,
        [string]$Header = 'ITEMS',
        [bool]$WriteToLog = $false,
        [bool]$ShowNumbers = $false
    )

    if (-not $Items -or $Items.Count -eq 0) {
        if ($WriteToLog) { Write-Log '  No items to display.' 'Yellow' }
        else { Write-Host '  No items to display.' -ForegroundColor Yellow }
        return
    }

    $totalBytes = ($Items | Measure-Object -Property SizeBytes -Sum).Sum

    if ($WriteToLog) {
        Write-Log ''
        Write-SectionHeader $Header
        Write-Log ''
        Write-Log ("  Total reclaimable space : {0}" -f (Format-Bytes $totalBytes)) 'Cyan'
        Write-Log ''
    } else {
        Write-Host ''
        Write-Host ('  ' + ('=' * 66)) -ForegroundColor Cyan
        Write-Host ("  {0}" -f $Header) -ForegroundColor Cyan
        Write-Host ('  ' + ('=' * 66)) -ForegroundColor Cyan
        Write-Host ''
        Write-Host ("  Total reclaimable space : {0}" -f (Format-Bytes $totalBytes)) -ForegroundColor Cyan
        Write-Host ''
    }

    $itemNum = 0
    $grouped = $Items | Group-Object Library
    foreach ($group in $grouped) {
        $groupBytes = ($group.Group | Measure-Object -Property SizeBytes -Sum).Sum
        if ($WriteToLog) {
            Write-Log ("  ┌── {0}" -f $group.Name) 'DarkCyan'
        } else {
            Write-Host ("  ┌── {0}" -f $group.Name) -ForegroundColor DarkCyan
        }
        foreach ($item in $group.Group) {
            $itemNum++
            $lastStr   = if ($item.LastPlayed) { $item.LastPlayed.ToString('yyyy-MM-dd') } else { 'never    ' }
            $svcLabel  = if ($item.Service) { "[{0}]" -f $item.Service } else { '[unmapped]' }
            $yearStr   = if ($item.Year -gt 0) { "({0})" -f $item.Year } else { '      ' }
            $titleFull = '{0} {1}' -f $item.Title, $yearStr
            $color     = if ($item.PlayCount -eq 0) { 'White' } else { 'DarkYellow' }
            $numPrefix = if ($ShowNumbers) { "{0,4}. " -f $itemNum } else { '  │  ' }
            $line      = "{0}{1,-52} Plays:{2,3}  Added:{3:yyyy-MM-dd}  Last:{4}  {5,10}  {6}" -f `
                $numPrefix, $titleFull, $item.PlayCount, $item.DateAdded, $lastStr, $item.SizeHuman, $svcLabel
            if ($WriteToLog) { Write-Log $line $color } else { Write-Host $line -ForegroundColor $color }
        }
        $footer = "  └── {0} item(s)  |  {1}" -f $group.Count, (Format-Bytes $groupBytes)
        if ($WriteToLog) { Write-Log $footer 'DarkCyan'; Write-Log '' }
        else { Write-Host $footer -ForegroundColor DarkCyan; Write-Host '' }
    }
}

# ================================================================
#  SHARED: Manual item selection parser
# ================================================================
function Select-ItemsForDeletion {
    param([array]$Items)

    # Display numbered list
    Show-ItemList -Items $Items -Header ('SELECT ITEMS TO DELETE -- {0} available' -f $Items.Count) -ShowNumbers $true

    Write-Host '  Enter item numbers to include, separated by commas.' -ForegroundColor Cyan
    Write-Host '  Ranges are supported (e.g. 1,3,5-8,12). Enter A to select all. Enter M to go back.' -ForegroundColor DarkGray
    Write-Host ''

    do {
        $input = (Read-Host '  Selection').Trim()

        if ($input.ToUpper() -eq 'M') { return $null }
        if ($input.ToUpper() -eq 'A') { return $Items }

        $selectedIndices = [System.Collections.Generic.List[int]]::new()
        $parseError = $false

        foreach ($token in ($input -split ',')) {
            $token = $token.Trim()
            if ($token -match '^(\d+)-(\d+)$') {
                $from = [int]$Matches[1]; $to = [int]$Matches[2]
                if ($from -lt 1 -or $to -gt $Items.Count -or $from -gt $to) {
                    Write-Host ("  Invalid range '{0}' -- valid range is 1-{1}" -f $token, $Items.Count) -ForegroundColor Red
                    $parseError = $true; break
                }
                for ($i = $from; $i -le $to; $i++) { if ($selectedIndices -notcontains $i) { $selectedIndices.Add($i) } }
            } elseif ($token -match '^\d+$') {
                $n = [int]$token
                if ($n -lt 1 -or $n -gt $Items.Count) {
                    Write-Host ("  Invalid number '{0}' -- valid range is 1-{1}" -f $token, $Items.Count) -ForegroundColor Red
                    $parseError = $true; break
                }
                if ($selectedIndices -notcontains $n) { $selectedIndices.Add($n) }
            } else {
                Write-Host ("  Could not parse '{0}' -- use numbers, ranges (e.g. 1-5), or A for all" -f $token) -ForegroundColor Red
                $parseError = $true; break
            }
        }

        if (-not $parseError -and $selectedIndices.Count -gt 0) {
            $selected = @($selectedIndices | Sort-Object | ForEach-Object { $Items[$_ - 1] })
            Write-Host ''
            Write-Host ("  {0} item(s) selected." -f $selected.Count) -ForegroundColor Cyan
            return $selected
        } elseif (-not $parseError) {
            Write-Host '  No items selected. Enter at least one number, or M to go back.' -ForegroundColor Yellow
        }
    } while ($true)
}

# ================================================================
#  DELETE (TOOL 2)
# ================================================================
function Invoke-Delete {
    param([array]$Items, [bool]$WithFiles)

    if (-not $Items -or $Items.Count -eq 0) {
        Write-Log '  No items to delete.' 'Yellow'
        return
    }

    Start-Log 'TrashBoy_Delete'

    $modeLabel = if ($WithFiles) { 'Delete from *arr + delete files' } else { 'Delete from *arr (keep files)' }
    Write-Log ''
    Write-Log '  ============================================================' 'Cyan'
    Write-Log ("   TrashBoy  |  Live Delete -- {0}" -f $modeLabel) 'Cyan'
    Write-Log ('   {0}' -f (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')) 'Cyan'
    Write-Log '  ============================================================' 'Cyan'
    Write-Log ''

    $totalBytes = ($Items | Measure-Object -Property SizeBytes -Sum).Sum
    Write-Log ("  Items queued    : {0}" -f $Items.Count) 'White'
    Write-Log ("  Estimated space : {0}" -f (Format-Bytes $totalBytes)) 'White'
    Write-Log ("  Delete files    : {0}" -f $WithFiles) $(if ($WithFiles) { 'Red' } else { 'Yellow' })
    Write-Log ''

    $warningText = if ($WithFiles) {
        "This will remove {0} item(s) from their *arr app AND delete all files from disk." -f $Items.Count
    } else {
        "This will remove {0} item(s) from their *arr app (files will remain on disk)." -f $Items.Count
    }

    if (-not (Confirm-LiveAction $warningText)) { return }

    Write-Log ''
    Write-SectionHeader 'DELETING'
    Write-Log ''

    $deleted = 0; $failed = 0; $skipped = 0
    $deletedItems = [System.Collections.Generic.List[PSObject]]::new()

    foreach ($item in $Items) {
        Write-Log ("  Processing: {0}  [{1}]" -f $item.Title, $item.Library) 'Cyan'

        $ok = $false
        switch ($item.Service) {
            'Radarr' {
                if (-not $Script:ConnectionStatus.Radarr) {
                    Write-Log '    Radarr not connected -- skipped' 'Yellow'; $skipped++; continue
                }
                $ok = Remove-ViaRadarr -Item $item -WithFiles $WithFiles
            }
            'Sonarr' {
                if (-not $Script:ConnectionStatus.Sonarr) {
                    Write-Log '    Sonarr not connected -- skipped' 'Yellow'; $skipped++; continue
                }
                $ok = Remove-ViaSonarr -Item $item -WithFiles $WithFiles
            }
            'Lidarr' {
                if (-not $Script:ConnectionStatus.Lidarr) {
                    Write-Log '    Lidarr not connected -- skipped' 'Yellow'; $skipped++; continue
                }
                $ok = Remove-ViaLidarr -Item $item -WithFiles $WithFiles
            }
            default {
                Write-Log ("    No *arr service mapped for library '{0}' -- skipped" -f $item.Library) 'Yellow'
                $skipped++
                continue
            }
        }

        if ($ok) { $deleted++; $deletedItems.Add($item) } else { $failed++ }
    }

    Write-Log ''
    Write-SectionHeader 'DELETE SUMMARY'
    Write-Log ''
    Write-Log ("  Deleted : {0}  item(s)" -f $deleted) 'Green'
    Write-Log ("  Failed  : {0}  item(s)" -f $failed)  $(if ($failed  -gt 0) { 'Red'    } else { 'Green' })
    Write-Log ("  Skipped : {0}  item(s)" -f $skipped) $(if ($skipped -gt 0) { 'Yellow' } else { 'Green' })

    # ── Plex library rescan ────────────────────────────────────────────────────
    if ($deletedItems.Count -gt 0 -and $WithFiles) {
        $sectionsToRefresh = @($deletedItems |
            ForEach-Object { $_.PlexSectionId } |
            Sort-Object -Unique)

        Write-Log ''
        Write-Log ("  Notifying Plex to rescan {0} library section(s)..." -f $sectionsToRefresh.Count) 'Cyan'

        foreach ($sectionId in $sectionsToRefresh) {
            # Find the library name for display
            $libName = ($deletedItems | Where-Object { $_.PlexSectionId -eq $sectionId } |
                Select-Object -First 1).Library
            try {
                Invoke-PlexApi -Path "/library/sections/$sectionId/refresh" | Out-Null
                Write-Log ("  [RESCAN]   '{0}' (section {1})" -f $libName, $sectionId) 'Green'
            } catch {
                Write-Log ("  [RESCAN FAILED]  '{0}' (section {1}) -- {2}" -f $libName, $sectionId, $_) 'Yellow'
            }
        }
    } elseif ($deletedItems.Count -gt 0 -and -not $WithFiles) {
        Write-Log ''
        Write-Log '  Plex rescan skipped -- files were not deleted, library contents unchanged.' 'DarkGray'
    }
    # ──────────────────────────────────────────────────────────────────────────

    Write-Log ''
    Write-Log ("  Log saved to: {0}" -f $Script:LogFile) 'Cyan'
}

# ================================================================
#  SETTINGS VIEWER (TOOL 3)
# ================================================================
function Show-Settings {
    Write-Log ''
    Write-SectionHeader 'CURRENT SETTINGS'
    Write-Log ''
    Write-Log '  From TrashBoy.config.ps1:' 'DarkGray'
    Write-Log ''
    Write-Log ("  Plex base URL      : {0}" -f $PlexConfig.BaseUrl) 'White'
    Write-Log ''

    if ($TautulliConfig.Enabled) {
        Write-Log ("  Tautulli           : Enabled") 'White'
        Write-Log ("  Tautulli URL       : {0}" -f $TautulliConfig.BaseUrl) 'White'
        Write-Log ("  MinWatchedPercent  : {0}%  (plays below this are not counted)" -f $TautulliConfig.MinWatchedPercent) 'White'
    } else {
        Write-Log '  Tautulli           : Disabled (using Plex viewCount)' 'DarkGray'
    }

    Write-Log ''
    Write-Log ("  Max play count     : {0}  (items with <= this many plays are flagged)" -f $ScanConfig.MaxPlayCount) 'White'
    Write-Log ("  Sort by            : {0}" -f $ScanConfig.SortBy) 'White'
    Write-Log ''

    Write-Log '  *arr Services:' 'DarkGray'
    foreach ($pair in @(
        @{ Name = 'Sonarr'; Cfg = $SonarrConfig }
        @{ Name = 'Radarr'; Cfg = $RadarrConfig }
        @{ Name = 'Lidarr'; Cfg = $LidarrConfig }
    )) {
        $status = if ($pair.Cfg.Enabled) { 'Enabled' } else { 'Disabled' }
        $color  = if ($pair.Cfg.Enabled) { 'White'   } else { 'DarkGray' }
        Write-Log ("  {0,-8}  {1,-10}  {2}" -f $pair.Name, $status, $pair.Cfg.BaseUrl) $color
    }

    Write-Log ''
    Write-Log '  Library Map:' 'DarkGray'
    foreach ($lib in $LibraryMap.Keys | Sort-Object) {
        Write-Log ("  {0,-35} → {1}" -f $lib, $LibraryMap[$lib]) 'White'
    }
    Write-Log ''
    Write-Log '  To change settings, edit TrashBoy.config.ps1 and restart TrashBoy.' 'DarkGray'
    Write-Log ''
}

# ================================================================
#  MAIN MENU
# ================================================================
function Show-MainMenu {
    param($SessionLog)
    Write-Host ''
    Write-Host '  ============================================================' -ForegroundColor Cyan
    Write-Host '   TrashBoy  |  Plex Unwatched Media Cleanup' -ForegroundColor Cyan
    Write-Host '  ============================================================' -ForegroundColor Cyan
    Write-Host ''
    Write-Host '  (1) Scan Libraries    -- find unwatched media and show a report'
    Write-Host '  (2) Delete Unwatched  -- remove flagged items via Sonarr/Radarr/Lidarr'
    Write-Host '  (3) Settings          -- view current configuration'
    Write-Host '  (M) Return to menu    -- (use from any sub-menu)'  -ForegroundColor DarkGray
    Write-Host '  (Q) Quit TrashBoy'                                 -ForegroundColor DarkGray
    Write-Host ''

    # Connection status widget
    Write-Host '  Connections:' -ForegroundColor DarkGray
    $plexColor = if ($Script:ConnectionStatus.Plex) { 'Green' } else { 'Red' }
    Write-Host ("    {0,-10}  {1}" -f 'Plex', $(if ($Script:ConnectionStatus.Plex) { 'OK' } else { 'UNREACHABLE' })) -ForegroundColor $plexColor

    if ($TautulliConfig.Enabled) {
        $tColor = if ($Script:ConnectionStatus.Tautulli) { 'Green' } else { 'Red' }
        $tLabel = if ($Script:ConnectionStatus.Tautulli) {
            "OK  (play source: Tautulli, min {0}% watched)" -f $TautulliConfig.MinWatchedPercent
        } else {
            'UNREACHABLE  (falling back to Plex viewCount)'
        }
        Write-Host ("    {0,-10}  {1}" -f 'Tautulli', $tLabel) -ForegroundColor $tColor
    } else {
        Write-Host ("    {0,-10}  Disabled  (play source: Plex viewCount)" -f 'Tautulli') -ForegroundColor DarkGray
    }

    foreach ($pair in @(
        @{ Name = 'Sonarr'; Cfg = $SonarrConfig; Key = 'Sonarr' }
        @{ Name = 'Radarr'; Cfg = $RadarrConfig; Key = 'Radarr' }
        @{ Name = 'Lidarr'; Cfg = $LidarrConfig; Key = 'Lidarr' }
    )) {
        if (-not $pair.Cfg.Enabled) {
            Write-Host ("    {0,-10}  Disabled" -f $pair.Name) -ForegroundColor DarkGray
        } else {
            $ok    = $Script:ConnectionStatus[$pair.Key]
            $color = if ($ok) { 'Green' } else { 'Red' }
            Write-Host ("    {0,-10}  {1}" -f $pair.Name, $(if ($ok) { 'OK' } else { 'UNREACHABLE' })) -ForegroundColor $color
        }
    }

    if ($Script:LastScanResults -ne $null) {
        Write-Host ''
        $reclaimable = Format-Bytes (($Script:LastScanResults | Measure-Object -Property SizeBytes -Sum).Sum)
        Write-Host ("  Last scan: {0} item(s) flagged, {1} reclaimable" -f `
            $Script:LastScanResults.Count, $reclaimable) `
            -ForegroundColor $(if ($Script:LastScanResults.Count -gt 0) { 'Yellow' } else { 'Green' })
    }

    Write-Host ''

    if ($SessionLog.Count -gt 0) {
        Write-Host '  This session:' -ForegroundColor DarkGray
        foreach ($entry in $SessionLog) {
            Write-Host ("    {0}" -f $entry) -ForegroundColor DarkGray
        }
        Write-Host ''
    }
}

# ================================================================
#  ENTRY POINT
# ================================================================
$SessionLog             = [System.Collections.Generic.List[string]]::new()
$Script:QuitRequested   = $false
$Script:ReturnedToMenu  = $false
$Script:ToolStartTime   = $null
$Script:LastScanResults = $null

function Add-SessionEntry ([string]$Entry) {
    $time = Get-Date -Format 'HH:mm'
    if ($Script:ToolStartTime) {
        $elapsed = (Get-Date) - $Script:ToolStartTime
        $elapsedStr = if ($elapsed.TotalMinutes -ge 1) {
            '{0}m {1}s' -f [int]$elapsed.TotalMinutes, $elapsed.Seconds
        } else {
            '{0}s' -f [int]$elapsed.TotalSeconds
        }
        $SessionLog.Add(("[{0}] {1}  ({2})" -f $time, $Entry, $elapsedStr))
    } else {
        $SessionLog.Add(("[{0}] {1}" -f $time, $Entry))
    }
    $Script:ToolStartTime = $null
}

do {
    Show-MainMenu $SessionLog
    do { $menuChoice = (Read-Host '  Choice').ToUpper() } until ($menuChoice -in '1','2','3','M','Q')

    if ($menuChoice -eq 'Q') { $Script:QuitRequested = $true; break }
    if ($menuChoice -eq 'M') { continue }

    switch ($menuChoice) {

        '1' {
            $Script:ToolStartTime = Get-Date

            $allLibraries    = Get-PlexLibraries
            $mappedLibraries = @($allLibraries | Where-Object { $LibraryMap.ContainsKey($_.title) })
            $libNames        = @($mappedLibraries | ForEach-Object { $_.title })

            $scopeOptions = @('All libraries') + $libNames
            $scopeChoice  = Select-SubMode 'Select scan scope:' $scopeOptions -Title 'Scan Libraries'
            if ($scopeChoice -eq  0) { $Script:ReturnedToMenu = $true; break }
            if ($scopeChoice -eq -1) { $Script:QuitRequested  = $true; break }

            $filterLibs = @()
            if ($scopeChoice -gt 1) {
                $filterLibs = @($libNames[$scopeChoice - 2])
            }

            $results    = Invoke-UnwatchedScan -FilterLibraries $filterLibs
            $scopeLabel = if ($filterLibs.Count -gt 0) { $filterLibs -join ', ' } else { 'All' }
            Add-SessionEntry ("Scan [{0}] -- {1} item(s) flagged" -f $scopeLabel, $(if ($results) { $results.Count } else { 0 }))
        }

        '2' {
            if (-not $Script:LastScanResults -or $Script:LastScanResults.Count -eq 0) {
                Write-Host ''
                Write-Host '  No scan results available. Run a Scan first (option 1).' -ForegroundColor Yellow
                Write-Host ''
                $Script:ReturnedToMenu = $true; break
            }

            $Script:ToolStartTime = Get-Date

            # ── Step 1: choose scope ──────────────────────────────────────────
            $deleteScope = Select-SubMode 'Select scope -- you will review items and confirm before anything is deleted:' @(
                ("All libraries  -- {0} item(s) flagged" -f $Script:LastScanResults.Count)
                'Choose a specific library'
            ) -Title 'Delete Unwatched'
            if ($deleteScope -eq  0) { $Script:ReturnedToMenu = $true; break }
            if ($deleteScope -eq -1) { $Script:QuitRequested  = $true; break }

            $itemsToDelete = $Script:LastScanResults
            $selectedLib   = 'All'

            if ($deleteScope -eq 2) {
                $groupNames   = @($Script:LastScanResults | Group-Object Library | ForEach-Object { $_.Name })
                $libChoice    = Select-SubMode 'Select library:' $groupNames -Title 'Delete Unwatched  >  Choose Library'
                if ($libChoice -eq  0) { $Script:ReturnedToMenu = $true; break }
                if ($libChoice -eq -1) { $Script:QuitRequested  = $true; break }
                $selectedLib   = $groupNames[$libChoice - 1]
                $itemsToDelete = @($Script:LastScanResults | Where-Object { $_.Library -eq $selectedLib })
            }

            # ── Step 2: show what would be deleted ───────────────────────────
            $scopeLabel = if ($selectedLib -eq 'All') {
                'All libraries -- {0} item(s)' -f $itemsToDelete.Count
            } else {
                '{0} -- {1} item(s)' -f $selectedLib, $itemsToDelete.Count
            }
            Show-ItemList -Items $itemsToDelete -Header ("FLAGGED ITEMS -- {0}" -f $scopeLabel)

            Write-Host '  You will be asked to type YES before anything is deleted.' -ForegroundColor DarkGray
            Write-Host ''

            # ── Step 3: selection mode ────────────────────────────────────────
            $selectionMode = Select-SubMode 'Select items to delete:' @(
                ("All {0} item(s) listed above" -f $itemsToDelete.Count)
                'Manually select items by number'
            ) -Title 'Delete Unwatched'
            if ($selectionMode -eq  0) { $Script:ReturnedToMenu = $true; break }
            if ($selectionMode -eq -1) { $Script:QuitRequested  = $true; break }

            if ($selectionMode -eq 2) {
                $itemsToDelete = Select-ItemsForDeletion -Items $itemsToDelete
                if ($null -eq $itemsToDelete) { $Script:ReturnedToMenu = $true; break }
            }

            # ── Step 4: choose mode ───────────────────────────────────────────
            $modeChoice = Select-SubMode 'Select delete mode:' @(
                'Remove from *arr only  -- item removed from app, files stay on disk'
                'Remove from *arr + delete files  -- PERMANENT, files gone from disk'
            ) -Title 'Delete Unwatched'
            if ($modeChoice -eq  0) { $Script:ReturnedToMenu = $true; break }
            if ($modeChoice -eq -1) { $Script:QuitRequested  = $true; break }

            $withFiles = ($modeChoice -eq 2)
            Invoke-Delete -Items $itemsToDelete -WithFiles $withFiles

            $modeStr = if ($withFiles) { 'with files' } else { 'keep files' }
            Add-SessionEntry ("Delete [{0}] [{1}] -- {2} item(s)" -f $modeStr, $selectedLib, $itemsToDelete.Count)
        }

        '3' {
            Show-Settings
            $Script:ReturnedToMenu = $true
        }
    }

    if ($Script:QuitRequested) { break }

    if (-not $Script:ReturnedToMenu) {
        Write-Host ''
        Write-Host '  Press M for main menu, or any other key to continue...' -ForegroundColor DarkGray
        $key = $Host.UI.RawUI.ReadKey('NoEcho,IncludeKeyDown')
        if ($key.Character -eq 'M' -or $key.Character -eq 'm') { }
    }
    $Script:ReturnedToMenu = $false

} while (-not $Script:QuitRequested)

Write-Host ''
Write-Host '  All done. Thanks for using TrashBoy -- enjoy the reclaimed space!' -ForegroundColor Cyan
Write-Host ''
